name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: success
        run: exit 0

  build2:
    runs-on: ubuntu-latest

    steps:
      - name: success
        run: exit 0

  build3:
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: success
        run: exit 0

  completed:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build
      - build2
      - build3

    steps:
      - name: Check job1 result and fail if job1 failed
        run: |
          if [ "${{ needs.build.result }}" == "failure" ]; then
            exit 1 
          fi

          if [ "${{ needs.build2.result }}" == "failure" ]; then
            exit 1 
          fi

          if [ "${{ needs.build3.result }}" == "failure" ]; then
            exit 1 
          fi

      - name: check
        run: echo completed
