name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: success
        run: exit 0

  matrix:
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [0, 1, 2]
    steps:
      - name: success
        run: exit ${{ matrix.number }}

  build3:
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: success
        run: exit 0

  completed:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build
      - matrix
      - build3

    steps:
      - name: Check needs results and fail if any of the job failed
        run: |
          if [ "${{ contains(needs.*.result, 'failure') }}" == "true" ]; then
            exit 1 
          fi

      - name: check
        run: echo completed
