name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: failure
        run: exit 1

  build2:
    runs-on: ubuntu-latest

    steps:
      - name: success
        run: exit 0

  completed:
    runs-on: ubuntu-latest
    needs:
      - build
      - build2

    steps:
      - name: echo
        run: echo completed
