name: slow CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: success
        run: exit 0

  slow-job:
    runs-on: ubuntu-latest

    steps:
      - name: sleep
        run: sleep 300
      - name: fail
        run: exit 1

  completed:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build
      - slow-job

    steps:
      - name: Check needs results and fail if any of the job failed
        run: |
          if [ "${{ contains(needs.*.result, 'failure') }}" == "true" ]; then
            exit 1 
          fi

      - name: check
        run: echo completed
