name: slow CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  # This workflow contains a single job called "build"
  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  completed:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs:
      - build
      - build2

    steps:
      - name: success
        run: exit 0

  slow-job:
    runs-on: ubuntu-latest

    steps:
      - name: sleep
        run: sleep 300
      - name: fail
        run: exit 1

  completed:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - build
      - slow-job

    steps:
      - name: Check needs results and fail if any of the job failed
        run: |
          if [ "${{ contains(needs.*.result, 'failure') }}" == "true" ]; then
            exit 1 
          fi

      - name: check
        run: echo completed
